# Scraping Data from API and making Data Frame and doing Text Preprocessing

## Importing Libraries

In [1]:
import requests
import pandas as pd
import string

## Scraping Data and Making Data Frame

### URL for API request of Movies

In [2]:
url = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1"

### Fetching data from API and converting to JSON and take a look at data

In [3]:
response = requests.get(url)
data = response.json()

In [4]:
data.keys()

dict_keys(['page', 'results', 'total_pages', 'total_results'])

In [5]:
data['results'][0]['id']

278

In [6]:
for key, value in data.items():
    print(f"{key}: {value}")

page: 1
results: [{'adult': False, 'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg', 'genre_ids': [18, 80], 'id': 278, 'original_language': 'en', 'original_title': 'The Shawshank Redemption', 'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'popularity': 29.7348, 'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', 'release_date': '1994-09-23', 'title': 'The Shawshank Redemption', 'video': False, 'vote_average': 8.715, 'vote_count': 29633}, {'adult': False, 'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg', 'genre_ids': [18, 80], 'id': 238, 'original_language': 'en', 'original_title': 'The Godfather', 'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', 'popularity': 26.9596, 'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'release_date': '1972-03-14', 'title': 'The Godfather', 'video': False, 'vote_average': 8.687, 'vote_count': 22382}, {'adult': False, 'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg', 'genre_ids': [18, 80], 'id': 240, 'original_language': 'en', 'original_title': 'The Godfather Part II', 'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'popularity': 15.031, 'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', 'release_date': '1974-12-20', 'title': 'The Godfather Part II', 'video': False, 'vote_average': 8.57, 'vote_count': 13538}, {'adult': False, 'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg', 'genre_ids': [18, 36, 10752], 'id': 424, 'original_language': 'en', 'original_title': "Schindler's List", 'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', 'popularity': 16.8997, 'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', 'release_date': '1993-12-15', 'title': "Schindler's List", 'video': False, 'vote_average': 8.566, 'vote_count': 17059}, {'adult': False, 'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg', 'genre_ids': [18], 'id': 389, 'original_language': 'en', 'original_title': '12 Angry Men', 'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.", 'popularity': 11.6829, 'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg', 'release_date': '1957-04-10', 'title': '12 Angry Men', 'video': False, 'vote_average': 8.554, 'vote_count': 9701}, {'adult': False, 'backdrop_path': '/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg', 'genre_ids': [16, 10751, 14], 'id': 129, 'original_language': 'ja', 'original_title': '千と千尋の神隠し', 'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 'popularity': 20.3403, 'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'release_date': '2001-07-20', 'title': 'Spirited Away', 'video': False, 'vote_average': 8.533, 'vote_count': 17892}, {'adult': False, 'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg', 'genre_ids': [28, 80, 53], 'id': 155, 'original_language': 'en', 'original_title': 'The Dark Knight', 'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', 'popularity': 27.9093, 'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'release_date': '2008-07-16', 'title': 'The Dark Knight', 'video': False, 'vote_average': 8.526, 'vote_count': 35091}, {'adult': False, 'backdrop_path': '/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg', 'genre_ids': [35, 18, 10749], 'id': 19404, 'original_language': 'hi', 'original_title': 'दिलवाले दुल्हनिया ले जायेंगे', 'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', 'popularity': 6.4511, 'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg', 'release_date': '1995-10-20', 'title': 'Dilwale Dulhania Le Jayenge', 'video': False, 'vote_average': 8.516, 'vote_count': 4550}, {'adult': False, 'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg', 'genre_ids': [14, 18, 80], 'id': 497, 'original_language': 'en', 'original_title': 'The Green Mile', 'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.", 'popularity': 22.6863, 'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg', 'release_date': '1999-12-10', 'title': 'The Green Mile', 'video': False, 'vote_average': 8.504, 'vote_count': 18787}, {'adult': False, 'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg', 'genre_ids': [35, 53, 18], 'id': 496243, 'original_language': 'ko', 'original_title': '기생충', 'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", 'popularity': 25.4063, 'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'release_date': '2019-05-30', 'title': 'Parasite', 'video': False, 'vote_average': 8.5, 'vote_count': 20053}, {'adult': False, 'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg', 'genre_ids': [12, 14, 28], 'id': 122, 'original_language': 'en', 'original_title': 'The Lord of the Rings: The Return of the King', 'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b', 'popularity': 25.1086, 'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 'release_date': '2003-12-17', 'title': 'The Lord of the Rings: The Return of the King', 'video': False, 'vote_average': 8.493, 'vote_count': 25951}, {'adult': False, 'backdrop_path': '/96hiUXEuYsu4tcnvlaY8tEMFM0m.jpg', 'genre_ids': [53, 80, 35], 'id': 680, 'original_language': 'en', 'original_title': 'Pulp Fiction', 'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.", 'popularity': 22.0578, 'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg', 'release_date': '1994-09-10', 'title': 'Pulp Fiction', 'video': False, 'vote_average': 8.486, 'vote_count': 29615}, {'adult': False, 'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg', 'genre_ids': [16, 10749, 18], 'id': 372058, 'original_language': 'ja', 'original_title': '君の名は。', 'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.', 'popularity': 18.7861, 'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg', 'release_date': '2016-08-26', 'title': 'Your Name.', 'video': False, 'vote_average': 8.478, 'vote_count': 12256}, {'adult': False, 'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg', 'genre_ids': [37], 'id': 429, 'original_language': 'it', 'original_title': 'Il buono, il brutto, il cattivo', 'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', 'popularity': 10.9392, 'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', 'release_date': '1966-12-22', 'title': 'The Good, the Bad and the Ugly', 'video': False, 'vote_average': 8.468, 'vote_count': 9379}, {'adult': False, 'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg', 'genre_ids': [12, 18, 878], 'id': 157336, 'original_language': 'en', 'original_title': 'Interstellar', 'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', 'popularity': 44.7344, 'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'release_date': '2014-11-05', 'title': 'Interstellar', 'video': False, 'vote_average': 8.466, 'vote_count': 38748}, {'adult': False, 'backdrop_path': '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg', 'genre_ids': [35, 18, 10749], 'id': 13, 'original_language': 'en', 'original_title': 'Forrest Gump', 'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', 'popularity': 19.0863, 'poster_path': '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg', 'release_date': '1994-06-23', 'title': 'Forrest Gump', 'video': False, 'vote_average': 8.462, 'vote_count': 29169}, {'adult': False, 'backdrop_path': '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg', 'genre_ids': [18, 80], 'id': 769, 'original_language': 'en', 'original_title': 'GoodFellas', 'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.', 'popularity': 15.6776, 'poster_path': '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg', 'release_date': '1990-09-12', 'title': 'GoodFellas', 'video': False, 'vote_average': 8.452, 'vote_count': 13966}, {'adult': False, 'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg', 'genre_ids': [28, 18], 'id': 346, 'original_language': 'ja', 'original_title': '七人の侍', 'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.", 'popularity': 6.9676, 'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg', 'release_date': '1954-04-26', 'title': 'Seven Samurai', 'video': False, 'vote_average': 8.449, 'vote_count': 4092}, {'adult': False, 'backdrop_path': '/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg', 'genre_ids': [16, 18, 10752], 'id': 12477, 'original_language': 'ja', 'original_title': '火垂るの墓', 'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.', 'popularity': 0.0088, 'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg', 'release_date': '1988-04-16', 'title': 'Grave of the Fireflies', 'video': False, 'vote_average': 8.443, 'vote_count': 6322}, {'adult': False, 'backdrop_path': '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg', 'genre_ids': [35, 18], 'id': 637, 'original_language': 'it', 'original_title': 'La vita è bella', 'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.', 'popularity': 10.5, 'poster_path': '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg', 'release_date': '1997-12-20', 'title': 'Life Is Beautiful', 'video': False, 'vote_average': 8.441, 'vote_count': 13759}]
total_pages: 532
total_results: 10628

In [7]:
data['results'][0]['title']

'The Shawshank Redemption'

In [8]:
data['results'][0]['overview']

'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.'

In [9]:
data['results'][0]['genre_ids']

[18, 80]

In [10]:
type(data['results'])

list

In [11]:
len(data['results'])

20

In [12]:
for i in data['results']:
    print(i['title'])

The Shawshank Redemption
The Godfather
The Godfather Part II
Schindler's List
12 Angry Men
Spirited Away
The Dark Knight
Dilwale Dulhania Le Jayenge
The Green Mile
Parasite
The Lord of the Rings: The Return of the King
Pulp Fiction
Your Name.
The Good, the Bad and the Ugly
Interstellar
Forrest Gump
GoodFellas
Seven Samurai
Grave of the Fireflies
Life Is Beautiful

### Fetching Genre Data

In [13]:
genres_url = "https://api.themoviedb.org/3/genre/movie/list?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US"
genres_response = requests.get(genres_url)
genres_data = genres_response.json()

### Making Data Frame for Movies with Genre Names

In [14]:
df_genres = pd.DataFrame(genres_data['genres'], columns=['id', 'name'])

In [15]:
df_genres

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

### Movies with Genre Names Data Frame

In [16]:
df_movies = pd.DataFrame()

In [17]:
df_movies['Title'] = []
df_movies['Overview'] = []
df_movies['Genre'] = []

In [18]:
df_movies

Empty DataFrame
Columns: [Title, Overview, Genre]
Index: []

In [19]:
df_movies['Title'] = "mani"

In [20]:
df_movies['Title']

Series([], Name: Title, dtype: object)

In [21]:
genre_list = []

In [22]:
data['results'][0]['genre_ids']

[18, 80]

In [23]:
df_genres

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [24]:
for i in data['results'][0]['genre_ids']:
    genre_list.append(df_genres[df_genres['id']==i]['name'].values[0])

In [25]:
genre_list

['Drama', 'Crime']

In [26]:
','.join(genre_list)

'Drama,Crime'

### Fetching Top Rated Movies Data from API (500 Pages) with Genre Names

In [27]:
# movies with genre names list
movie_list = []
genre_list = []

# loop to iterate through 500 pages
for page in range(1,501):

    # url to fetch top rated movies
    url = f"https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={page}"
    # getting response from the API
    response = requests.get(url)
    # covering response to json
    data = response.json()

    # loop to iterate throough each movie in results
    for movie in data['results']:

        # loop to get Genre Names from Genre IDs and adding to list
        for genre_id in movie['genre_ids']:
            # extracting genre name from genre id
            genre_name = df_genres[df_genres['id']==genre_id]['name'].values[0]

            # checking if genre name is already in the list or not
            if genre_name not in genre_list:
                genre_list.append(genre_name)

        # adding movie details to movie list
        movie_list.append({
            'Title': movie['title'],
            'Overview': movie['overview'],
            'Genres': ', '.join(genre_list)
        })

# creating dataframe from movie list
df_movies = pd.DataFrame(movie_list)

In [28]:
df_movies

,Title,Overview,Genres
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama, Crime"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama, Crime"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama, Crime"
3,Schindler's List,The true story of how businessman Oskar Schind...,"Drama, Crime, History, War"
4,12 Angry Men,The defense and the prosecution have rested an...,"Drama, Crime, History, War"
...,...,...,...
9995,The Farm,The young couple Nora and Alec are on their wa...,"Drama, Crime, History, War, Animation, Family,..."
9996,Silent House,Sarah returns with her father and uncle to fix...,"Drama, Crime, History, War, Animation, Family,..."
9997,The Next Karate Kid,"Mr. Miyagi decides to take Julie, a troubled t...","Drama, Crime, History, War, Animation, Family,..."
9998,Bachelorette,Three friends are asked to be bridesmaids at a...,"Drama, Crime, History, War, Animation, Family,..."
9999,The Emoji Movie,"Gene, a multi-expressional emoji, sets out on ...","Drama, Crime, History, War, Animation, Family,..."

In [29]:
df_movies.shape

(10000, 3)

## Text Data Preprocessing

### Lowercase Conversion

In [30]:
df_movies['Overview'] = df_movies['Overview'].str.lower()

In [31]:
df_movies['Genres'] = df_movies['Genres'].str.lower()

In [32]:
df_movies['Title'] = df_movies['Title'].str.lower()

In [33]:
df_movies

,Title,Overview,Genres
0,the shawshank redemption,imprisoned in the 1940s for the double murder ...,"drama, crime"
1,the godfather,"spanning the years 1945 to 1955, a chronicle o...","drama, crime"
2,the godfather part ii,in the continuing saga of the corleone crime f...,"drama, crime"
3,schindler's list,the true story of how businessman oskar schind...,"drama, crime, history, war"
4,12 angry men,the defense and the prosecution have rested an...,"drama, crime, history, war"
...,...,...,...
9995,the farm,the young couple nora and alec are on their wa...,"drama, crime, history, war, animation, family,..."
9996,silent house,sarah returns with her father and uncle to fix...,"drama, crime, history, war, animation, family,..."
9997,the next karate kid,"mr. miyagi decides to take julie, a troubled t...","drama, crime, history, war, animation, family,..."
9998,bachelorette,three friends are asked to be bridesmaids at a...,"drama, crime, history, war, animation, family,..."
9999,the emoji movie,"gene, a multi-expressional emoji, sets out on ...","drama, crime, history, war, animation, family,..."

In [34]:
df_movies

,Title,Overview,Genres
0,the shawshank redemption,imprisoned in the 1940s for the double murder ...,"drama, crime"
1,the godfather,"spanning the years 1945 to 1955, a chronicle o...","drama, crime"
2,the godfather part ii,in the continuing saga of the corleone crime f...,"drama, crime"
3,schindler's list,the true story of how businessman oskar schind...,"drama, crime, history, war"
4,12 angry men,the defense and the prosecution have rested an...,"drama, crime, history, war"
...,...,...,...
9995,the farm,the young couple nora and alec are on their wa...,"drama, crime, history, war, animation, family,..."
9996,silent house,sarah returns with her father and uncle to fix...,"drama, crime, history, war, animation, family,..."
9997,the next karate kid,"mr. miyagi decides to take julie, a troubled t...","drama, crime, history, war, animation, family,..."
9998,bachelorette,three friends are asked to be bridesmaids at a...,"drama, crime, history, war, animation, family,..."
9999,the emoji movie,"gene, a multi-expressional emoji, sets out on ...","drama, crime, history, war, animation, family,..."

### Checking for HTML Tags in 'Overview' Column

In [35]:
# Check for HTML tags in Overview column
import re
html_pattern = r'<[^>]+>'
df_movies['has_html'] = df_movies['Overview'].str.contains(html_pattern, regex=True, na=False)
print(f"Rows with HTML tags in Overview: {df_movies['has_html'].sum()}")

Rows with HTML tags in Overview: 0

In [36]:
df_movies.drop(columns=['has_html'], inplace=True)

In [37]:
df_movies

,Title,Overview,Genres
0,the shawshank redemption,imprisoned in the 1940s for the double murder ...,"drama, crime"
1,the godfather,"spanning the years 1945 to 1955, a chronicle o...","drama, crime"
2,the godfather part ii,in the continuing saga of the corleone crime f...,"drama, crime"
3,schindler's list,the true story of how businessman oskar schind...,"drama, crime, history, war"
4,12 angry men,the defense and the prosecution have rested an...,"drama, crime, history, war"
...,...,...,...
9995,the farm,the young couple nora and alec are on their wa...,"drama, crime, history, war, animation, family,..."
9996,silent house,sarah returns with her father and uncle to fix...,"drama, crime, history, war, animation, family,..."
9997,the next karate kid,"mr. miyagi decides to take julie, a troubled t...","drama, crime, history, war, animation, family,..."
9998,bachelorette,three friends are asked to be bridesmaids at a...,"drama, crime, history, war, animation, family,..."
9999,the emoji movie,"gene, a multi-expressional emoji, sets out on ...","drama, crime, history, war, animation, family,..."

### Search url in Text

In [38]:
# Check for URLs in Overview column
url_pattern = r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'

df_movies['has_url'] = df_movies['Overview'].str.contains(
    url_pattern, regex=True, na=False
)

In [39]:
df_movies['has_url'].sum()

np.int64(0)

In [40]:
df_movies.drop(columns=['has_url'], inplace=True)

In [41]:
df_movies

,Title,Overview,Genres
0,the shawshank redemption,imprisoned in the 1940s for the double murder ...,"drama, crime"
1,the godfather,"spanning the years 1945 to 1955, a chronicle o...","drama, crime"
2,the godfather part ii,in the continuing saga of the corleone crime f...,"drama, crime"
3,schindler's list,the true story of how businessman oskar schind...,"drama, crime, history, war"
4,12 angry men,the defense and the prosecution have rested an...,"drama, crime, history, war"
...,...,...,...
9995,the farm,the young couple nora and alec are on their wa...,"drama, crime, history, war, animation, family,..."
9996,silent house,sarah returns with her father and uncle to fix...,"drama, crime, history, war, animation, family,..."
9997,the next karate kid,"mr. miyagi decides to take julie, a troubled t...","drama, crime, history, war, animation, family,..."
9998,bachelorette,three friends are asked to be bridesmaids at a...,"drama, crime, history, war, animation, family,..."
9999,the emoji movie,"gene, a multi-expressional emoji, sets out on ...","drama, crime, history, war, animation, family,..."

### Removing Punctuation

In [42]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [43]:
def remove_punct(text):
    translator = str.maketrans('', '', string.punctuation)
    text = text.translate(translator)
    return text

In [44]:
df_movies['Overview'] = df_movies['Overview'].apply(remove_punct)

In [45]:
df_movies['Genres'] = df_movies['Genres'].apply(remove_punct)

In [46]:
df_movies['Title'] = df_movies['Title'].apply(remove_punct)

In [47]:
df_movies.iloc[0]['Title']

'the shawshank redemption'

In [48]:
df_movies.iloc[0]['Overview']

'imprisoned in the 1940s for the double murder of his wife and her lover upstanding banker andy dufresne begins a new life at the shawshank prison where he puts his accounting skills to work for an amoral warden during his long stretch in prison dufresne comes to be admired by the other inmates  including an older prisoner named red  for his integrity and unquenchable sense of hope'

### Removing Stop Words

In [65]:
import nltk

In [66]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [67]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

In [68]:
def remove_stopwords(text):
    cleaned_text = [word for word in text.split() if word not in stop_words]
    return ' '.join(cleaned_text)

In [69]:
text = "The cat is sitting on the mat"
remove_stopwords(text)
# Output: "cat sitting mat"

'The cat sitting mat'

In [70]:
df_movies['Overview'] = df_movies['Overview'].apply(remove_stopwords)

In [71]:
df_movies['Genres'] = df_movies['Genres'].apply(remove_stopwords)

In [72]:
df_movies['Title'] = df_movies['Title'].apply(remove_stopwords)

In [73]:
df_movies

,Title,Overview,Genres
0,shawshank redemption,imprisoned 1940s double murder wife lover upst...,drama crime
1,godfather,spanning years 1945 1955 chronicle fictional i...,drama crime
2,godfather part ii,continuing saga corleone crime family young vi...,drama crime
3,schindlers list,true story businessman oskar schindler saved t...,drama crime history war
4,12 angry men,defense prosecution rested jury filing jury ro...,drama crime history war
...,...,...,...
9995,farm,young couple nora alec way back long road trip...,drama crime history war animation family fanta...
9996,silent house,sarah returns father uncle fix familys longtim...,drama crime history war animation family fanta...
9997,next karate kid,mr miyagi decides take julie troubled teenager...,drama crime history war animation family fanta...
9998,bachelorette,three friends asked bridesmaids wedding woman ...,drama crime history war animation family fanta...
9999,emoji movie,gene multiexpressional emoji sets journey beco...,drama crime history war animation family fanta...

### Removing Stemming

In [84]:
from nltk.stem import PorterStemmer

In [85]:
ps = PorterStemmer()
def stemming(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [87]:
sentence = "walk walking walked walks"
stem =  stemming(sentence)
print(stem)

walk walk walk walk

In [88]:
df_movies['Title'] = df_movies['Title'].apply(stemming)
df_movies['Overview'] = df_movies['Overview'].apply(stemming)
df_movies['Genres'] = df_movies['Genres'].apply(stemming)

### Lemmatization

In [93]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [94]:
lemmatizer = WordNetLemmatizer()

In [95]:
def lemmatize_text(text):
    words = text.split()
    lammatized = [lemmatizer.lemmatize(word,pos='v') for word in words]
    return ' '.join(lammatized)

In [96]:
df_movies['Title'] = df_movies['Title'].apply(lemmatize_text)
df_movies['Overview'] = df_movies['Overview'].apply(lemmatize_text)
df_movies['Genres'] = df_movies['Genres'].apply(lemmatize_text)

### Tokenization

In [97]:
from nltk.tokenize import word_tokenize

In [98]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [99]:
def apply_token(text):
    return word_tokenize(text)

In [100]:
df_movies['Title_Token'] = df_movies['Title'].apply(apply_token)
df_movies['Overview_Token'] = df_movies['Overview'].apply(apply_token)
df_movies['Genres_Token'] = df_movies['Genres'].apply(apply_token)